version: '3.9'
services:
  db:
    container_name: album-maker-mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: album_maker_mysql
    healthcheck:
      test: "mysqladmin -p$$MYSQL_ROOT_PASSWORD ping"
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
  backend:
    depends_on:
      - db
    container_name: album-maker-backend
    build: ./backend
    ports:
      - 5100:4000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    restart: always
  client:
    depends_on:
      - backend
    build: ./client
    container_name: album-maker-client
    ports:
      - 5000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    restart: always
  
volumes:
  dbdata: